# Generated by Django 2.1.1 on 2019-04-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODOClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_column='TD_state', max_length=1)),
                ('duedate', models.DateField(blank=True, db_column='TD_duedate', null=True)),
                ('text', models.CharField(db_column='TD_text', max_length=300)),
            ],
            options={
                'db_table': 'TODO',
                'managed': True,
            },
        ),
    ]
