# Generated by Django 2.1.1 on 2019-04-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepperRestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoclass',
            options={},
        ),
        migrations.AlterModelTable(
            name='todoclass',
            table=None,
        ),
    ]
