# Generated by Django 2.1.1 on 2019-04-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepperRestApp', '0002_auto_20190423_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoclass',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='todoclass',
            table='TODO',
        ),
    ]
