# Generated by Django 2.1.1 on 2019-04-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepperRestApp', '0003_auto_20190423_2326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TODOClass',
            new_name='TODOs',
        ),
    ]
