# Generated by Django 2.2 on 2019-04-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepperRestApp', '0004_auto_20190423_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='duedate',
            new_name='td_duedate',
        ),
        migrations.RenameField(
            model_name='todos',
            old_name='state',
            new_name='td_state',
        ),
        migrations.RenameField(
            model_name='todos',
            old_name='text',
            new_name='td_text',
        ),
    ]
